name: lyon1mail
description: Une librairie mail dédiée pour Lyon1
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dartz: ^0.10.1
  dotenv: ^4.0.1
  enough_mail: ^2.1.1
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0  #latest version
  requests: ^4.7.0


